version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - backend
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
